import streamlit as st
from utils.risk_engine import score_lease_readiness_dict
from utils.app_common import page_header, risk_badge
from utils.audit import init_session_audit_log, create_audit_record, append_audit_record

page_header("Lease Operations", "Real Estate Intake Readiness and Operational Triage", "Simulated lease and real-estate operations workflow automation prototype. Not legal advice.")

init_session_audit_log(st.session_state)

with st.form("lease_ops_form"):
    st.subheader("Lease Intake & Readiness Form")

    c1, c2 = st.columns(2)
    with c1:
        lease_id = st.text_input("Lease ID", value="LSE-DEMO-001")
        property_name = st.text_input("Property Name", value="Fictional Commerce Plaza")
        property_type = st.selectbox("Property Type", ["Office", "Retail", "Industrial", "Medical", "Mixed-use", "Other"])
        unit_type = st.selectbox("Unit Type", ["Suite", "Floor", "Warehouse Bay", "Kiosk", "Lab", "Other"])
        tenant_stage = st.selectbox("Tenant Stage", ["Prospect", "LOI", "Draft Lease", "Negotiation", "Ready for Signature", "Pre-Move-In"])

    with c2:
        legal_names_confirmed = st.checkbox("Legal names confirmed", value=False)
        move_in_date_confirmed = st.checkbox("Move-in date confirmed", value=False)
        deposit_status_confirmed = st.checkbox("Deposit status confirmed", value=False)
        utilities_confirmed = st.checkbox("Utilities confirmed", value=False)
        parking_confirmed = st.checkbox("Parking confirmed", value=False)
        pets_occupants_confirmed = st.checkbox("Pets/additional occupants confirmed", value=False)
        insurance_confirmed = st.checkbox("Insurance confirmed", value=False)

    operational_issues = st.text_area(
        "Operational Issues / Notes",
        height=140,
        value="Access hours are still being finalized and utility account transfer date is pending.",
    )

    submitted = st.form_submit_button("Run Lease Readiness Assessment")

if submitted:
    payload = {
        "lease_id": lease_id,
        "property_name": property_name,
        "property_type": property_type,
        "unit_type": unit_type,
        "tenant_stage": tenant_stage,
        "legal_names_complete": "Yes" if legal_names_confirmed else "No",
        "move_in_date": "2026-08-01" if move_in_date_confirmed else "Unknown",
        "deposit_status": "Confirmed" if deposit_status_confirmed else "Unknown",
        "utilities_clarity": "Clear" if utilities_confirmed else "Unclear",
        "parking_terms_known": "Yes" if parking_confirmed else "Unknown",
        "pets_policy_known": "Yes" if pets_occupants_confirmed else "Unknown",
        "additional_occupants_known": "Yes" if pets_occupants_confirmed else "Unknown",
        "insurance_status": "Current" if insurance_confirmed else "Missing",
        "operational_issues": operational_issues,
    }

    result = score_lease_readiness_dict(payload)

    st.subheader("Lease Readiness Outcome")
    m1, m2, m3 = st.columns(3)
    m1.metric("Lease-Readiness Score", result["risk_score"])
    m2.metric("Risk Level", risk_badge(result["risk_level"]))
    m3.metric("Human Review Required", "Yes" if result["human_review_required"] else "No")

    st.write("**Escalation Route:**", result["escalation_route"])

    tab1, tab2, tab3, tab4 = st.tabs([
        "Missing Fields",
        "Next Steps",
        "Escalation Triggers",
        "Simulated Follow-up Email",
    ])

    with tab1:
        for missing in result["missing_facts"] or ["No missing fields detected."]:
            st.write(f"- {missing}")

    with tab2:
        for step in result["recommended_next_steps"]:
            st.write(f"- {step}")

    with tab3:
        triggers = result["triggered_rules"] or ["No escalation triggers activated."]
        for trigger in triggers:
            st.write(f"- {trigger}")

    with tab4:
        email_body = f"""Subject: Lease Readiness Follow-up - {lease_id}

Hi Operations and Legal Team,

This is a simulated workflow follow-up for {property_name} ({property_type}, {unit_type}).
Current tenant stage: {tenant_stage}.

Readiness assessment result:
- Risk level: {result['risk_level']}
- Readiness score: {result['risk_score']}
- Human review required: {'Yes' if result['human_review_required'] else 'No'}
- Escalation route: {result['escalation_route']}

Outstanding items:
- """ + "\n- ".join(result["missing_facts"] or ["None"]) + """

Recommended actions:
- """ + "\n- ".join(result["recommended_next_steps"]) + """

Operational note:
""" + operational_issues + """

This message is generated by a simulated portfolio workflow and is not legal advice.
"""
        st.code(email_body, language="text")

    decision = "Escalate" if result["risk_level"] == "High" else "Review" if result["risk_level"] == "Medium" else "Approve"
    audit_event = create_audit_record(
        workflow_id=f"WF-{lease_id}",
        module="Lease Operations",
        input_category="Lease",
        risk_result=result,
        decision_status=decision,
    )
    append_audit_record(st.session_state, audit_event)
    st.success("Lease workflow event added to session-state audit log.")

    report_text = f"""AI Legal & Operations Workflow Studio - Simulated Lease Operations Report
Disclaimer: Simulation only. Not legal advice.

Lease ID: {lease_id}
Property: {property_name}
Property Type: {property_type}
Unit Type: {unit_type}
Tenant Stage: {tenant_stage}

Readiness Score: {result['risk_score']}
Risk Level: {result['risk_level']}
Human Review Required: {result['human_review_required']}
Escalation Route: {result['escalation_route']}
Recommended Decision: {decision}

Missing Fields:
- """ + "\n- ".join(result["missing_facts"] or ["None"]) + """

Escalation Triggers:
- """ + "\n- ".join(result["triggered_rules"] or ["None"]) + """

Recommended Next Steps:
- """ + "\n- ".join(result["recommended_next_steps"]) + """

Operational Issues:
""" + operational_issues + """
"""

    st.download_button(
        "Download Lease Operations Report",
        data=report_text.encode("utf-8"),
        file_name=f"lease_ops_{lease_id}.txt",
        mime="text/plain",
    )

st.caption("Disclaimer: Simulated AI workflow prototype; not legal advice.")
